[build]
  publish = "out"  # Output directory for Next.js static export
  command = "npm install --include=dev && npm run generate:content && npm run build"  # Install dependencies, generate content, and build

[build.environment]
  NODE_ENV = "production"
  # Force installation of devDependencies for Tailwind CSS
  NPM_FLAGS = "--include=dev"

# Build caching for faster deployments
[build.caching]
  # Cache node_modules to speed up installs
  package_json = true
  # Cache Next.js build artifacts
  build_dependencies = ["node_modules/.cache/next"]

# Redirects for SPA (Single Page Application) behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
