[build]
  publish = ".next"  # Output directory for Next.js build
  command = "npm install --include=dev && npm run build"  # Install devDependencies and build

[build.environment]
  NODE_ENV = "production"
  # Force installation of devDependencies for Tailwind CSS
  NPM_FLAGS = "--include=dev"

# Build caching for faster deployments
[build.caching]
  # Cache node_modules to speed up installs
  package_json = true
  # Cache Next.js build artifacts
  build_dependencies = ["node_modules/.cache/next"]

# Ignore backend directories to avoid processing Python files
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"  # For Netlify Functions (optional)
  status = 200

# Additional settings for optimal performance
[functions]
  node_bundler = "esbuild"  # Faster bundling for functions

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"